### ISSUE TITLE
ページネーションの実装

### ISSUE THREAD

**Issue by S-Yamamoto3215** [S-Yamamoto3215/awesome_events#29]
### やること
- [x] Gemの導入(Kaminari)
- [x] コントローラーの修正
- [x] kaminariのviewをBootstrap仕様に変更
- [x] i18nで日本語化

**Comment by S-Yamamoto3215** [comment]
## Gemの導入(Kaminari)

- Gemfileに`gem 'kaminari'`を追加
- bundle install

kaminariの公式
https://github.com/kaminari/kaminari

**Comment by S-Yamamoto3215** [comment]
## コントローラーの修正

ページネーションを実装するモデルに`.page().per()`をつなげることでviewでページネーションが実装できるようになる。

`.page()`は何ページ目かを渡す必要がある。
ページネーションの1やnextをクリックした時に渡されるものなのでparams[:page]を渡すと良い。

`per()`は1ベージあたり何件表示するかを決めます。

**Comment by S-Yamamoto3215** [comment]
## kaminariのviewをBootstrap仕様に変更
kaminariのテンプレートは以下のコマンドで生成可能。
`rails g kaminari:views default`

bootstrapの見た目にしたいので
`rails g kaminari:views bootstrap4`を実行

しかし、bootstrap4の方はエラーになった。
やむを得ず、kaminari_themesのリポジトリからbootstrap4のviewをcloneし
所定の位置へ配置して反映させた。

**Comment by S-Yamamoto3215** [comment]
## i18nで日本語化
`config/locales/kaminari_ja.yml`を作成

公式に記載されている設定できる値は以下の通り。

```
en:
  views:
    pagination:
      first: "&laquo; First"
      last: "Last &raquo;"
      previous: "&lsaquo; Prev"
      next: "Next &rsaquo;"
      truncate: "&hellip;"
  helpers:
    page_entries_info:
      one_page:
        display_entries:
          zero: "No %{entry_name} found"
          one: "Displaying <b>1</b> %{entry_name}"
          other: "Displaying <b>all %{count}</b> %{entry_name}"
      more_pages:
        display_entries: "Displaying %{entry_name} <b>%{first}&nbsp;-&nbsp;%{last}</b> of <b>%{total}</b> in total"
```

今回はviews:pagination以下だけを設定
